[project]
name = "gallery_view"
authors = [
    { name = "Chetan Nahar", email = "chetan2nahar@gmail.com"}
]
description = "This app helps us to display the gallery like view for each doctype which contains the fieldname `gallery_html`."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
